
version: "3"
services:
  prerender:
    build: ./prerender-docker
    image: prerender
    ports:
      - 4000:3000
    links:
      - app
  haproxy:
    image: haproxy:1.7.5-alpine
    volumes:
      - ./reverse-proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./reverse-proxy/log:/dev/log:rw
    ports:
      - 5000:80
    links:
      - app
      - prerender
  app:
    image: nginx
    volumes:
      - ./app/app:/usr/share/nginx/html
    ports:
      - 8080:80
  varnish:
    build: ./varnish
    image: varnish
    ports:
      - 6000:80
      - 7000:6081
      - 8000:8080
    links:
      - haproxy
      - prerender
      - app
        
  
